CREATE USER bread IDENTIFIED BY bread DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA 10M ON users;
GRANT connect, resource, create session, create table, create view to bread;

CREATE TABLE breads(
    id NUMBER NOT NULL,
    TYPE VARCHAR2(20) NOT NULL,
    CALORIES NUMBER(20) NOT NULL,
    STOCK NUMBER,
    PRIMARY KEY (ID) 
);


INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(0,'bread',200,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(1,'Italian',200,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(2,'Flatbread',220,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(3,'Monterey Cheddar',240,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(4,'Italian Herbcheese',250,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(5,'Grain Wheat',210,10);

INSERT INTO breads(ID, TYPE, CALORIES,STOCK)
VALUES(6,'Honey Oat',260,10);

commit;
